# Generated by Django 5.2.4 on 2025-08-04 21:49

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[reviews.validators.ReviewRatingValidator()]),
        ),
    ]
