# Generated by Django 5.2.4 on 2025-07-24 10:51

import cars.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('horse_power', models.PositiveIntegerField()),
                ('year', models.DateField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0, message='The price cannot be negative')])),
                ('engine_size', models.IntegerField(validators=[cars.validators.CarEngineSizeValidator()])),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon')], max_length=30)),
                ('fuel_type', models.CharField(choices=[('gas', 'Gasoline'), ('diesel', 'Diesel'), ('el', 'Electric'), ('hyb', 'Hybrid'), ('other', 'Other')], default='other', max_length=10)),
                ('image', models.ImageField(upload_to='cars/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
