# Generated by Django 5.2.4 on 2025-08-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
