# Generated by Django 5.2.4 on 2025-08-04 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'permissions': [('approve_car', 'Can approve car')]},
        ),
    ]
