# Generated by Django 5.2.4 on 2025-08-05 14:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='car_main_image'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='car_extra_image'),
        ),
    ]
