# Generated by Django 5.2.4 on 2025-07-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_rename_user_booking_owner_booking_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
