# Generated by Django 5.2.4 on 2025-07-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='owner',
            new_name='booker',
        ),
    ]
